# Generated by Django 4.1.2 on 2022-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=13124, max_digits=10),
            preserve_default=False,
        ),
    ]
