# Generated by Django 4.1.2 on 2022-11-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_order_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
    ]
