# Generated by Django 4.1.2 on 2022-11-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_remove_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='imsages.jpeg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images.jpeg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='images.jpeg', upload_to='images'),
            preserve_default=False,
        ),
    ]
