# Generated by Django 4.1.2 on 2022-11-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_food_image_profile_image_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=32423423),
            preserve_default=False,
        ),
    ]
