# Generated by Django 4.1.2 on 2022-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0007_deliveryed_delete_deliveryboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(to='delivery_boy.fooditem'),
        ),
    ]
